# SWEEP SETTINGS
project: yolo-eyes-andrea # Project name

method: grid  # Can be 'random' or 'grid'

parameters:
  batch_size:
    values: [32]
  lr:
    values: [0.0001, 0.00001]
  epochs:
    values: [500]
  optimizer:
    values: ['Adam', 'SGD']

metric:
  goal: minimize
  name: validation_loss

early_terminate:
  type: hyperband
  min_iter: 5  
  s: 2  

#run_cap: 2
#concurrency: 2 #number of concurrent processes
