                                                  ############################################################

                                                  #                  VIDEO LABELLING STEP

                                                  ############################################################

# PATHS
input_folder_lab: 
    'D:/nyst_video_cartelle'
flattened_folder_lab: 
    'D:/nyst_flatten_video'  
output_folder_lab:
    'D:/nyst_labelled_videos'

# VALUES CONFIGURATION
clip_duration:
    10
overlapping:
    8

                                                  ############################################################

                                                  #             VIDEO FEATURES EXTRACTION STEP

                                                  ############################################################
# PATHS
input_folder_extr:
    'D:/nyst_labelled_videos/videos'
output_folder_extr:
    'D:/nyst_labelled_videos'
  

                                                  ############################################################

                                                  #             PREPROCESS AND AUGMENTATION STEP

                                                  ############################################################  
# PATHS
csv_input_file:
    '/repo/porri/nyst_labelled_videos/video_features.csv'
csv_label_file:
    'D:/nyst_labelled_videos/labels.csv'

                                                  ############################################################

                                                  #                   TRAINING FULL NET STEP

                                                  ############################################################  

save_path:
    '/repo/porri/nyst_labelled_videos/best_model.pth'
save_path_info:
    '/repo/porri/nyst_labelled_videos'
save_path_wb:
    '/repo/porri/nyst/models'
