                                                  ############################################################

                                                  #                  VIDEO LABELLING STEP

                                                  ############################################################

# PATHS
input_folder_lab: 
    'D:/nyst_video_cartelle'
flattened_folder_lab: 
    'D:/nyst_flatten_video'  
output_folder_lab:
    'D:/nyst_labelled_videos'

# VALUES CONFIGURATION
clip_duration:
    10
overlapping:
    8

                                                  ############################################################

                                                  #             VIDEO FEATURES EXTRACTION STEP

                                                  ############################################################
# PATHS
input_folder_extr:
    'D:/nyst_labelled_videos_prove/test'
output_folder_extr:
    'D:/nyst_labelled_videos'

                                                  ############################################################

                                                  #             PREPROCESS AND AUGMENTATION STEP

                                                  ############################################################  
# PATHS
csv_input_file:
    'D:/nyst_labelled_videos/video_features.csv'
csv_label_file:
    'D:/nyst_labelled_videos/labels.csv'
new_csv_file:
    'D:/nyst_labelled_videos/merged_data.csv'

# VALUES CONFIGURATION
preprocess:
    ['cubic_interpolation']
augmentation:
    ['augment_data']    
                                                  ############################################################

                                                  #                TRAINING FULL NET STEPS

                                                  ############################################################
# PATHS

save_path:
    'D:/nyst_labelled_videos/best_model.pth'
save_path_info:
    'D:/nyst_labelled_videos'
save_path_wb:
    'D:/models'
