# SWEEP SETTINGS
project: nyst_detection

method: grid  # Può essere 'random' o 'grid'

parameters:
  batch_size:
    values: [8, 16, 32]
  lr:
    values: [0.001, 0.0001, 0.00001]
  epochs:
    values: [50]
  threshold_correct:
    values: [0.5]
  patience:
    values: [5]
  optimizer:
    values: ['adam', 'sgd']
  criterion:
    values: ['BCELoss', 'MSELoss']

metric:
  goal: minimize
  name: validation_loss

early_terminate:
  type: hyperband
  min_iter: 5  # Almeno 5 iterazioni prima di iniziare a scartare run
  s: 2        # Parametro opzionale per controllare la quantità di risorse allocate

#run_cap: 2
concurrency: 2
