# SWEEP SETTINGS
project: nyst_detection

method: grid  # Can be 'random' or 'grid'

parameters:
  batch_size:
    values: [8, 16, 32]
  lr:
    values: [0.001, 0.0001, 0.00001]
  epochs:
    values: [50]
  threshold_correct:
    values: [0.5]
  patience:
    values: [5, 10]
  threshold_correct:
    values: [0.5]
  optimizer:
    values: ['adam', 'sgd']
  criterion:
    values: ['BCELoss', 'MSELoss']

metric:
  goal: minimize
  name: validation_loss

early_terminate:
  type: hyperband
  min_iter: 5  
  s: 2  

#run_cap: 2
concurrency: 2 #number of concurrent processes
